from enum import Enum


class ErrorCode(str, Enum):
    NOT_FOUND = "NOT_FOUND"
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    EXPIRED = "EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    # Trading
    TRADING_DISABLED = "TRADING_DISABLED"
    ORDER_LIMIT_EXCEEDED = "ORDER_LIMIT_EXCEEDED"
    INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
    ORDER_REJECTED = "ORDER_REJECTED"
    ORDER_CANCEL_FAILED = "ORDER_CANCEL_FAILED"

    # MCP
    MCP_CONNECTION_ERROR = "MCP_CONNECTION_ERROR"
    MCP_TOOL_ERROR = "MCP_TOOL_ERROR"

    # Agent
    AGENT_CYCLE_ERROR = "AGENT_CYCLE_ERROR"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"
    LLM_ERROR = "LLM_ERROR"

    # Recommendation
    RECOMMENDATION_EXPIRED = "RECOMMENDATION_EXPIRED"
    RECOMMENDATION_ALREADY_PROCESSED = "RECOMMENDATION_ALREADY_PROCESSED"
