"""add_trading_rules_table

Revision ID: 506d4ef486ca
Revises: e6f885d3ac30
Create Date: 2026-03-10 09:58:18.947695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506d4ef486ca'
down_revision: Union[str, None] = 'e6f885d3ac30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('strategy_type', sa.String(length=30), nullable=False),
    sa.Column('param_name', sa.String(length=50), nullable=False),
    sa.Column('param_value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_report_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_rules_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_rules_rule_type'), ['rule_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_rules_rule_type'))
        batch_op.drop_index(batch_op.f('ix_trading_rules_is_active'))

    op.drop_table('trading_rules')
    # ### end Alembic commands ###
