"""add_agent_activity_and_daily_report_tables

Revision ID: 7d1d8019ed2c
Revises: aa7e2dac9c85
Create Date: 2026-02-26 12:50:15.187832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1d8019ed2c'
down_revision: Union[str, None] = 'aa7e2dac9c85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_cycles', sa.Integer(), nullable=False),
    sa.Column('total_analyses', sa.Integer(), nullable=False),
    sa.Column('total_recommendations', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('win_count', sa.Integer(), nullable=False),
    sa.Column('loss_count', sa.Integer(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('market_summary', sa.Text(), nullable=True),
    sa.Column('performance_review', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('next_day_plan', sa.Text(), nullable=True),
    sa.Column('top_picks', sa.Text(), nullable=True),
    sa.Column('strategy_stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_reports_report_date'), ['report_date'], unique=True)

    op.create_table('agent_activity_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=True),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('stock_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=30), nullable=True),
    sa.Column('llm_tier', sa.String(length=10), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_activity_logs_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_activity_logs_cycle_id'), ['cycle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_activity_logs_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_agent_activity_logs_activity_type'))

    op.drop_table('agent_activity_logs')
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_report_date'))

    op.drop_table('daily_reports')
    # ### end Alembic commands ###
