"""drop dead tables: orders, portfolios, portfolio_holdings, recommendations

Revision ID: 9c9291c406e1
Revises: 4a8c2f1e9b3d
Create Date: 2026-06-22 02:33:43.283126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9291c406e1'
down_revision: Union[str, None] = '4a8c2f1e9b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_holdings_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_holdings_stock_id'))

    op.drop_table('portfolio_holdings')
    op.drop_table('portfolios')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_status'))
        batch_op.drop_index(batch_op.f('ix_recommendations_stock_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_stock_id'))

    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('portfolio_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('stock_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('side', sa.VARCHAR(length=10), nullable=False),
    sa.Column('order_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('source', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('filled_quantity', sa.INTEGER(), nullable=False),
    sa.Column('filled_price', sa.FLOAT(), nullable=False),
    sa.Column('kis_order_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('filled_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('stock_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('analysis_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), nullable=False),
    sa.Column('suggested_price', sa.FLOAT(), nullable=False),
    sa.Column('suggested_quantity', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_status'), ['status'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('mode', sa.VARCHAR(length=10), nullable=False),
    sa.Column('budget', sa.FLOAT(), nullable=False),
    sa.Column('cash', sa.FLOAT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('portfolio_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('stock_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('avg_buy_price', sa.FLOAT(), nullable=False),
    sa.Column('current_price', sa.FLOAT(), nullable=False),
    sa.Column('unrealized_pnl', sa.FLOAT(), nullable=False),
    sa.Column('unrealized_pnl_rate', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_holdings_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_holdings_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###
