"""add judgment_verifications table and trading_rules.expected_effect

Revision ID: a5157c49a8fe
Revises: d6a2bc1c5ea4
Create Date: 2026-07-04 00:21:12.154052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5157c49a8fe'
down_revision: Union[str, None] = 'd6a2bc1c5ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judgment_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('judgment_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('judged_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('judgment_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judgment_verifications_judgment_type'), ['judgment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_judgment_verifications_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_judgment_verifications_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_judgment_verifications_verdict'), ['verdict'], unique=False)

    with op.batch_alter_table('trading_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_effect', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_rules', schema=None) as batch_op:
        batch_op.drop_column('expected_effect')

    with op.batch_alter_table('judgment_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judgment_verifications_verdict'))
        batch_op.drop_index(batch_op.f('ix_judgment_verifications_symbol'))
        batch_op.drop_index(batch_op.f('ix_judgment_verifications_source_id'))
        batch_op.drop_index(batch_op.f('ix_judgment_verifications_judgment_type'))

    op.drop_table('judgment_verifications')
    # ### end Alembic commands ###
