"""add_untradeable_symbols_table

Revision ID: b2199105e3e1
Revises: b2c3d4e5f6g7
Create Date: 2026-04-21 17:16:53.147988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2199105e3e1'
down_revision: Union[str, None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('untradeable_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('untradeable_symbols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_untradeable_symbols_symbol'), ['symbol'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('untradeable_symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_untradeable_symbols_symbol'))

    op.drop_table('untradeable_symbols')
    # ### end Alembic commands ###
