"""add buy_count sell_count unrealized_pnl open_position_count to daily_reports

Revision ID: e6f885d3ac30
Revises: 7d1d8019ed2c
Create Date: 2026-03-04 17:55:51.797943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f885d3ac30'
down_revision: Union[str, None] = '7d1d8019ed2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('sell_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('unrealized_pnl', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('open_position_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_column('open_position_count')
        batch_op.drop_column('unrealized_pnl')
        batch_op.drop_column('sell_count')
        batch_op.drop_column('buy_count')

    # ### end Alembic commands ###
